//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWS.SimpleBank.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateDeposit : Account
    {
        public decimal Principal { get; set; }
        public int Term { get; set; }
        public System.DateTime MaturityDate { get; set; }
        public decimal APY { get; set; }
    }
}
